// tailwind.config.js
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "surface-container-highest": "#e4e1ee",
        "primary-container": "#4f46e5",
        "inverse-surface": "#302f39",
        "on-primary-container": "#dad7ff",
        "secondary-container": "#6cf8bb",
        "outline-variant": "#c7c4d8",
        surface: "#fcf8ff",
        "on-tertiary-fixed": "#141b2b",
        "on-tertiary-fixed-variant": "#404758",
        secondary: "#006c49",
        "surface-container": "#f0ecf9",
        "surface-tint": "#4d44e3",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#c3c0ff",
        "inverse-primary": "#c3c0ff",
        "on-secondary-container": "#00714d",
        "surface-container-low": "#f5f2ff",
        "on-error-container": "#93000a",
        "on-surface-variant": "#464555",
        primary: "#3525cd",
        outline: "#777587",
        "surface-container-high": "#eae6f4",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#596072",
        "on-tertiary-container": "#d5dbf0",
        "on-primary-fixed-variant": "#3323cc",
        "surface-bright": "#fcf8ff",
        "on-background": "#1b1b24",
        "on-secondary-fixed-variant": "#005236",
        "on-error": "#ffffff",
        "tertiary-fixed": "#dce2f7",
        "primary-fixed": "#e2dfff",
        "inverse-on-surface": "#f3effc",
        "secondary-fixed-dim": "#4edea3",
        "on-surface": "#1b1b24",
        tertiary: "#414859",
        background: "#fcf8ff",
        "surface-dim": "#dcd8e5",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#0f0069",
        "secondary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#c0c6db",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "12px",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        gutter: "24px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "h1-desktop": ["Space Grotesk", "sans-serif"],
        "h1-mobile": ["Space Grotesk", "sans-serif"],
        "h2-desktop": ["Space Grotesk", "sans-serif"],
        "h2-mobile": ["Space Grotesk", "sans-serif"],
        h3: ["Space Grotesk", "sans-serif"],
        eyebrow: ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "h1-desktop": ["56px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h1-mobile": ["42px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h2-desktop": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "h2-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        h3: ["24px", { lineHeight: "1.2", fontWeight: "500" }],
        eyebrow: ["12px", { lineHeight: "1.0", letterSpacing: "0.06em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      keyframes: {
        floating: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
      },
      animation: {
        floating: "floating 6s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};